#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Copyright (C) 2018-2022 Geraldo Ribeiro <geraldo@intmain.io>
# ----------------------------------------------------------------------

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
# Lista todos os arquivos gpg
password_files=( "$prefix"/**/*.gpg )
# Remove o a pasta
password_files=( "${password_files[@]#"$prefix"/}" )
# Remove a extensão
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -p "Senha:" -l 20 "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
  pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
    xdotool type --clearmodifiers --file -
fi

# vim: spelllang=pt,en
